<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
//X1 X2 JP
//X3 X4 SN
//X5 X6 EI
//X7 X8 FT
class QuestionSeeder extends Seeder
{
    public function run()
    {
        DB::table('questions')->insert([


            [
                'question' => '當你某日想去某個地方，你會？',
                'option_a' => '計劃好將做的事情以及何時做',
                'option_a_value' => 'J',
                'option_b' => '什麼都不想就去',
                'option_b_value' => 'P',
                'part' => 'part1',
            ],
            [
                'question' => '如果你是一位老師，你願教？',
                'option_a' => '涉及事實的課程',
                'option_a_value' => 'S',
                'option_b' => '涉及理論的課程',
                'option_b_value' => 'N',
                'part' => 'part1',
            ],
            [
                'question' => '你通常是？',
                'option_a' => '一個善於交際的人',
                'option_a_value' => 'E',
                'option_b' => '安靜缄默的人',
                'option_b_value' => 'I',
                'part' => 'part1',
            ],
            [
                'question' => '你喜歡？',
                'option_a' => '事先安排好約會，聚會等',
                'option_a_value' => 'J',
                'option_b' => '只要時機恰當就無拘無束地做任何有趣的事',
                'option_b_value' => 'P',
                'part' => 'part1',
            ],
            [
                'question' => '你通常和相處得更好？',
                'option_a' => '現實的人',
                'option_a_value' => 'S',
                'option_b' => '想象力豐富的人',
                'option_b_value' => 'N',
                'part' => 'part1',
            ],
            [
                'question' => '當你和一群人在一起時，你會？',
                'option_a' => '參加大家的談話',
                'option_a_value' => 'E',
                'option_b' => '只同你熟知的人單獨談話',
                'option_b_value' => 'I',
                'part' => 'part1',
            ],
            [
                'question' => '往往，你是？',
                'option_a' => '情感駕馭理智',
                'option_a_value' => 'F',
                'option_b' => '理智駕馭情感',
                'option_b_value' => 'T',
                'part' => 'part1',
            ],
            [
                'question' => '你更喜歡做多數事情？',
                'option_a' => '有計劃地',
                'option_a_value' => 'J',
                'option_b' => '即興時',
                'option_b_value' => 'P',
                'part' => 'part1',
            ],
            [
                'question' => '你願意自己被認為是一個？',
                'option_a' => '善於動手的人',
                'option_a_value' => 'S',
                'option_b' => '善於創意的人',
                'option_b_value' => 'N',
                'part' => 'part1',
            ],
            [
                'question' => '在大群體中，你常更多地？',
                'option_a' => '介紹他人',
                'option_a_value' => 'E',
                'option_b' => '由別人來介紹你',
                'option_b_value' => 'I',
                'part' => 'part1',
            ],
            [
                'question' => '按日程表辦事？',
                'option_a' => '正合你意',
                'option_a_value' => 'J',
                'option_b' => '束縛了你',
                'option_b_value' => 'P',
                'part' => 'part1',
            ],
            [
                'question' => '你更喜歡？',
                'option_a' => '務實且有豐富常識的人',
                'option_a_value' => 'S',
                'option_b' => '頭腦靈活的人',
                'option_b_value' => 'N',
                'part' => 'part1',
            ],
            [
                'question' => '你覺得通常別人要花費？',
                'option_a' => '一小段時間來了解你',
                'option_a_value' => 'E',
                'option_b' => '很久來了解你',
                'option_b_value' => 'I',
                'part' => 'part1',
            ],
            [
                'question' => '被稱為是更高的讚賞？',
                'option_a' => '感性的人',
                'option_a_value' => 'F',
                'option_b' => '一貫理性的人',
                'option_b_value' => 'T',
                'part' => 'part1',
            ],
            [
                'question' => '對於制定周末計劃，你覺得？',
                'option_a' => '很有必要',
                'option_a_value' => 'J',
                'option_b' => '沒必要',
                'option_b_value' => 'P',
                'part' => 'part1',
            ],
            [
                'question' => '你願把作為朋友？',
                'option_a' => '腳踏實地的人',
                'option_a_value' => 'S',
                'option_b' => '常有新觀點的人',
                'option_b_value' => 'N',
                'part' => 'part1',
            ],
            [
                'question' => '多數時候，你傾向於？',
                'option_a' => '同他人在一起',
                'option_a_value' => 'E',
                'option_b' => '獨處',
                'option_b_value' => 'I',
                'part' => 'part1',
            ],
            [
                'question' => '日常工作中，你喜歡？',
                'option_a' => '通常先安排好工作並加以完成，以免壓力過大',
                'option_a_value' => 'J',
                'option_b' => '在時間緊迫的情況下爭分奪秒地工作',
                'option_b_value' => 'P',
                'part' => 'part1',
            ],
            [
                'question' => '當你為了消遣而閱讀時，你？',
                'option_a' => '喜歡作者確切地表達其意思',
                'option_a_value' => 'S',
                'option_b' => '欣賞奇特新穎的表達方式',
                'option_b_value' => 'N',
                'part' => 'part1',
            ],
            [
                'question' => '你能否？',
                'option_a' => '只要願意就能輕鬆地同幾乎任何人說個沒完',
                'option_a_value' => 'E',
                'option_b' => '只能在特定場合下或同特定的人才願意講許多話',
                'option_b_value' => 'I',
                'part' => 'part1',
            ],
            [
                'question' => '你更傾向於？',
                'option_a' => '感性地做事',
                'option_a_value' => 'F',
                'option_b' => '依邏輯行事',
                'option_b_value' => 'T',
                'part' => 'part1',
            ],
            [
                'question' => '當有一項特殊工作時，你會？',
                'option_a' => '在開始前精心組織策劃',
                'option_a_value' => 'J',
                'option_b' => '在工作進行中找出必要環節',
                'option_b_value' => 'P',
                'part' => 'part1',
            ],
            [
                'question' => '做很多人都會做的事情時，你喜歡？',
                'option_a' => '按慣例做',
                'option_a_value' => 'S',
                'option_b' => '按自己獨創的方式做',
                'option_b_value' => 'N',
                'part' => 'part1',
            ],
            [
                'question' => '你新認識的人說出你的興趣所在？',
                'option_a' => '馬上就能',
                'option_a_value' => 'E',
                'option_b' => '只有當他們真正了解你之後才能',
                'option_b_value' => 'I',
                'part' => 'part1',
            ],
            [
                'question' => '在計劃一次旅行時，你更喜歡？',
                'option_a' => '事先就知道在大部分日子所將做的事情',
                'option_a_value' => 'J',
                'option_b' => '在多數情況下隨心所欲地行事',
                'option_b_value' => 'P',
                'part' => 'part1',
            ],
            [
                'question' => '多數人認為你？',
                'option_a' => '非常坦率',
                'option_a_value' => 'E',
                'option_b' => '不太把自己的事情告訴別人',
                'option_b_value' => 'I',
                'part' => 'part1',
            ],
            //PART2

            [
                'question' => '事實還是觀點？',
                'option_a' => '事實',
                'option_a_value' => 'S',
                'option_b' => '觀點',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '熱忱還是堅決？',
                'option_a' => '熱忱',
                'option_a_value' => 'F',
                'option_b' => '堅決',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '切實還是創新？',
                'option_a' => '切實',
                'option_a_value' => 'S',
                'option_b' => '創新',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '有計劃還是隨意？',
                'option_a' => '有計劃',
                'option_a_value' => 'J',
                'option_b' => '隨意',
                'option_b_value' => 'P',
                'part' => 'part2',
            ],
            [
                'question' => '實在還是抽象？',
                'option_a' => '實在',
                'option_a_value' => 'S',
                'option_b' => '抽象',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '感覺還是思考？',
                'option_a' => '感覺',
                'option_a_value' => 'F',
                'option_b' => '思考',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '已知的還是新穎的？',
                'option_a' => '已知的',
                'option_a_value' => 'S',
                'option_b' => '新穎的',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '感性還是理性？',
                'option_a' => '感性',
                'option_a_value' => 'F',
                'option_b' => '理性',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '安排好的還是不受限制的？',
                'option_a' => '安排好的',
                'option_a_value' => 'J',
                'option_b' => '不受限制的',
                'option_b_value' => 'P',
                'part' => 'part2',
            ],
            [
                'question' => '熱情還是安靜？',
                'option_a' => '熱情',
                'option_a_value' => 'E',
                'option_b' => '安靜',
                'option_b_value' => 'I',
                'part' => 'part2',
            ],
            [
                'question' => '溫柔還是堅硬？',
                'option_a' => '溫柔',
                'option_a_value' => 'F',
                'option_b' => '堅硬',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '陳述還是觀念？',
                'option_a' => '陳述',
                'option_a_value' => 'S',
                'option_b' => '觀念',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '慈悲心腸還是意志堅強？',
                'option_a' => '慈悲心腸',
                'option_a_value' => 'F',
                'option_b' => '意志堅強',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '事實的還是理論的？',
                'option_a' => '事實的',
                'option_a_value' => 'S',
                'option_b' => '理論的',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '很多朋友還是少許朋友？',
                'option_a' => '很多朋友',
                'option_a_value' => 'E',
                'option_b' => '少許朋友',
                'option_b_value' => 'I',
                'part' => 'part2',
            ],
            [
                'question' => '系統的還是自發的？',
                'option_a' => '系統的',
                'option_a_value' => 'J',
                'option_b' => '自發的',
                'option_b_value' => 'P',
                'part' => 'part2',
            ],
            [
                'question' => '確定還是推測？',
                'option_a' => '確定',
                'option_a_value' => 'S',
                'option_b' => '推測',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '寬容還是堅定？',
                'option_a' => '寬容',
                'option_a_value' => 'F',
                'option_b' => '堅定',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '必然性還是可能性？',
                'option_a' => '必然性',
                'option_a_value' => 'S',
                'option_b' => '可能性',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '動之以情還是曉之以理？',
                'option_a' => '動之以情',
                'option_a_value' => 'F',
                'option_b' => '曉之以理',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '健談還是缄默？',
                'option_a' => '健談',
                'option_a_value' => 'E',
                'option_b' => '缄默',
                'option_b_value' => 'I',
                'part' => 'part2',
            ],
            [
                'question' => '溫和還是力量？',
                'option_a' => '溫和',
                'option_a_value' => 'F',
                'option_b' => '力量',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '現實還是理想？',
                'option_a' => '現實',
                'option_a_value' => 'S',
                'option_b' => '理想',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '好心的還是稱職的？',
                'option_a' => '好心的',
                'option_a_value' => 'F',
                'option_b' => '稱職的',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '事實還是理論？',
                'option_a' => '事實',
                'option_a_value' => 'S',
                'option_b' => '理論',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '系統還是隨機？',
                'option_a' => '系統',
                'option_a_value' => 'J',
                'option_b' => '隨機',
                'option_b_value' => 'P',
                'part' => 'part2',
            ],
            [
                'question' => '現實的還是想象的？',
                'option_a' => '現實的',
                'option_a_value' => 'S',
                'option_b' => '想象的',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '易動情的還是客觀的？',
                'option_a' => '易動情的',
                'option_a_value' => 'F',
                'option_b' => '客觀的',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '建造還是發明？',
                'option_a' => '建造',
                'option_a_value' => 'S',
                'option_b' => '發明',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '感情豐富的還是注重實際的？',
                'option_a' => '感情豐富的',
                'option_a_value' => 'F',
                'option_b' => '注重實際的',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '有序的還是隨便的？',
                'option_a' => '有序的',
                'option_a_value' => 'J',
                'option_b' => '隨便的',
                'option_b_value' => 'P',
                'part' => 'part2',
            ],
            [
                'question' => '開朗還是文靜？',
                'option_a' => '開朗',
                'option_a_value' => 'E',
                'option_b' => '文靜',
                'option_b_value' => 'I',
                'part' => 'part2',
            ],
            [
                'question' => '認同還是分析？',
                'option_a' => '認同',
                'option_a_value' => 'F',
                'option_b' => '分析',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '事實的還是想象的？',
                'option_a' => '事實的',
                'option_a_value' => 'S',
                'option_b' => '想象的',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '祝福還是利益？',
                'option_a' => '祝福',
                'option_a_value' => 'F',
                'option_b' => '利益',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '詳實還是概括？',
                'option_a' => '詳實',
                'option_a_value' => 'S',
                'option_b' => '概括',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '決定還是衝動？',
                'option_a' => '決定',
                'option_a_value' => 'J',
                'option_b' => '衝動',
                'option_b_value' => 'P',
                'part' => 'part2',
            ],
            [
                'question' => '製作還是創造？',
                'option_a' => '製作',
                'option_a_value' => 'S',
                'option_b' => '創造',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '熱情還是客觀？',
                'option_a' => '熱情',
                'option_a_value' => 'F',
                'option_b' => '客觀',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '實用的還是迷人的？',
                'option_a' => '實用的',
                'option_a_value' => 'S',
                'option_b' => '迷人的',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '體諒的還是公正的？',
                'option_a' => '體諒的',
                'option_a_value' => 'F',
                'option_b' => '公正的',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '愛交際還是愛文靜？',
                'option_a' => '愛交際',
                'option_a_value' => 'E',
                'option_b' => '愛文靜',
                'option_b_value' => 'I',
                'part' => 'part2',
            ],
            [
                'question' => '敏感還是合理？',
                'option_a' => '敏感',
                'option_a_value' => 'F',
                'option_b' => '合理',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '製造還是設計？',
                'option_a' => '製造',
                'option_a_value' => 'S',
                'option_b' => '設計',
                'option_b_value' => 'N',
                'part' => 'part2',
            ],
            [
                'question' => '有同情心還是有邏輯頭腦？',
                'option_a' => '有同情心',
                'option_a_value' => 'F',
                'option_b' => '有邏輯頭腦',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            [
                'question' => '公開的還是私人的？',
                'option_a' => '公開的',
                'option_a_value' => 'E',
                'option_b' => '私人的',
                'option_b_value' => 'I',
                'part' => 'part2',
            ],
            [
                'question' => '同情憐憫還是深謀遠慮？',
                'option_a' => '同情憐憫',
                'option_a_value' => 'F',
                'option_b' => '深謀遠慮',
                'option_b_value' => 'T',
                'part' => 'part2',
            ],
            //PART3
            [
                'question' => '通常你更喜歡___？',
                'option_a' => '提前安排好業餘活動',
                'option_a_value' => 'J',
                'option_b' => '即興地做事情',
                'option_b_value' => 'P',
                'part' => 'part3',
            ],
            [
                'question' => '你覺得被許多人圍著___？',
                'option_a' => '讓你感到更有精神',
                'option_a_value' => 'E',
                'option_b' => '常讓你精力衰竭',
                'option_b_value' => 'I',
                'part' => 'part3',
            ],
            [
                'question' => '多數情況下，你更喜歡___？',
                'option_a' => '按日程表辦事',
                'option_a_value' => 'J',
                'option_b' => '順其自然',
                'option_b_value' => 'P',
                'part' => 'part3',
            ],
            [
                'question' => '在聚會中，你___？',
                'option_a' => '總是玩得很開心',
                'option_a_value' => 'E',
                'option_b' => '有時覺得無趣',
                'option_b_value' => 'I',
                'part' => 'part3',
            ],
            [
                'question' => '作決定時，對於你來說更重要的是___？',
                'option_a' => '考慮人們的感受和觀點',
                'option_a_value' => 'F',
                'option_b' => '權衡事實',
                'option_b_value' => 'T',
                'part' => 'part3',
            ],
            [
                'question' => '你喜歡___？',
                'option_a' => '事先很早就作好準備',
                'option_a_value' => 'J',
                'option_b' => '看清事態如何發展再作計劃',
                'option_b_value' => 'P',
                'part' => 'part3',
            ],
            [
                'question' => '別人了解你___？',
                'option_a' => '很容易',
                'option_a_value' => 'E',
                'option_b' => '很難',
                'option_b_value' => 'I',
                'part' => 'part3',
            ],
            [
                'question' => '你喜歡的處事方式是___？',
                'option_a' => '堅持那些已經有效的方法',
                'option_a_value' => 'S',
                'option_b' => '分析哪些仍有錯並挑戰未解決的問題',
                'option_b_value' => 'N',
                'part' => 'part3',
            ],
            [
                'question' => '你覺得自己更偏向於是一個___？',
                'option_a' => '有組織性的人',
                'option_a_value' => 'J',
                'option_b' => '自發性的人',
                'option_b_value' => 'P',
                'part' => 'part3',
            ],
            [
                'question' => '你___？',
                'option_a' => '只要願意，就能和幾乎任何一個人談個沒完',
                'option_a_value' => 'E',
                'option_b' => '只同和自己有共同興趣的人才能長時間的交談',
                'option_b_value' => 'I',
                'part' => 'part3',
            ],
            [
                'question' => '你願在一個 老闆（老師）手下工作（學習）___？',
                'option_a' => '脾氣好，但前後不一致',
                'option_a_value' => 'F',
                'option_b' => '對人嚴厲，但有條理',
                'option_b_value' => 'T',
                'part' => 'part3',
            ],
            [
                'question' => '你更喜歡按照___做大多數事情？',
                'option_a' => '已定的日程表',
                'option_a_value' => 'J',
                'option_b' => '當天的感覺',
                'option_b_value' => 'P',
                'part' => 'part3',
            ],
            [
                'question' => '在聚會中，你___？',
                'option_a' => '自己聊得多',
                'option_a_value' => 'E',
                'option_b' => '聽別人聊得多',
                'option_b_value' => 'I',
                'part' => 'part3',
            ],
            [
                'question' => '通常，你更喜歡上涉及___的課程？',
                'option_a' => '具體內容',
                'option_a_value' => 'S',
                'option_b' => '概念和原則',
                'option_b_value' => 'N',
                'part' => 'part3',
            ],
            [
                'question' => '當你開始了一項必須在一週內完成的大項目時，你會___？',
                'option_a' => '花時間列出所要做的事情及其先後次序',
                'option_a_value' => 'J',
                'option_b' => '直接開始',
                'option_b_value' => 'P',
                'part' => 'part3',
            ],
            [
                'question' => '在社交場合中，你通常覺得___？',
                'option_a' => '很容易同大多數人長時間談話',
                'option_a_value' => 'E',
                'option_b' => '同某些人很難開展和維持長時間的談話',
                'option_b_value' => 'I',
                'part' => 'part3',
            ],
            [
                'question' => '被稱為___是更高的讚賞？',
                'option_a' => '富有同情心',
                'option_a_value' => 'F',
                'option_b' => '有競爭力',
                'option_b_value' => 'T',
                'part' => 'part3',
            ],
            [
                'question' => '你覺得按計劃行事___？',
                'option_a' => '多數時候是有幫助的、適宜的',
                'option_a_value' => 'J',
                'option_b' => '有時必要，便令人不爽',
                'option_b_value' => 'P',
                'part' => 'part3',
            ],
            [
                'question' => '你通常___？',
                'option_a' => '同大家打成一片',
                'option_a_value' => 'E',
                'option_b' => '傾向於獨處',
                'option_b_value' => 'I',
                'part' => 'part3',
            ],
            [
                'question' => '總的來說，要完成一項重大任務，你傾向於___？',
                'option_a' => '開始先確定每一個步驟',
                'option_a_value' => 'J',
                'option_b' => '邊做邊考慮必須完成的事',
                'option_b_value' => 'P',
                'part' => 'part3',
            ],










            // 其他問題...
        ]);
    }
}
